---
- name: tomcat installation on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install java 11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: creating a tomcat group
      ansible.builtin.group:
        name: tomcat
    - name: creating a system user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        home: /opt/tomcat
        shell: /bin/false
        group: tomcat
        state: present
    - name: download and archieve tomcat
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.5/bin/apache-tomcat-10.1.5.tar.gz
        dest: /opt/tomcat/
        remote_src: yes
    - name: create a symbolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.5
        dest: /opt/tomcat/latest
        state: link
    - name: change ownership
      ansible.builtin.file:
        dest: /opt/tomcat
        owner: tomcat
        group: tomcat
        recurse: yes
        state: directory
    - name: adding execution permissions to ssh files
      ansible.builtin.shell: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
    - name: adding systemd file
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: tomcat
        group: tomcat
    - name: reload deamon
      ansible.builtin.systemd:
        name: tomcat
        daemon_reload: yes
        enabled: yes
        state: started
    - name: configure web configuration
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: /opt/tomcat/latest/conf/tomcat-users.xml
        owner: tomcat
        group: tomcat
    - name: configure manager app
      ansible.builtin.copy:
        src: manager-context.xml
        dest: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
        owner: tomcat
        group: tomcat
    - name: configure host manager app
      ansible.builtin.copy:
        src: context.xml
        dest: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
        owner: tomcat
        group: tomcat
    - name: reload deamon
      ansible.builtin.systemd:
        name: tomcat
        state: restarted